baseURL = 'https://jesus-castro89.github.io/ims_doc'
languageCode = 'es-mx'
title = 'CMS :: Implantación de Sistemas de Gestión de Contenidos'

[module]
[[module.imports]]
path = "github.com/colinwilson/lotusdocs"
disable = false
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
disable = false

[params]
google_fonts = [["Saira", "400", "700", "900"], ["Rosario", "400", "700"], ["Fira Code", "500, 700"]]
sans_serif_font = "Rosario"
secondary_font = "Saira"
mono_fonr = "Fira Code"
css = ["/ims_doc/css/custom.css"]

[params.footer]
copyright = "M. en E. Jesús Aurelio Castro Magaña"

[params.docs]
darkmode = true
themeColor = "blue"
sidebarIcons = true
titleIcon = true
prism = true

[[menu.primary]]
name  = "Docs"
url = "/docs/"
identifier = "docs"
weight = 10