name: Deploy Hugo site

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: actions/setup-hugo@v3
        with:
          hugo-version: "latest"

      - name: Build Hugo site
        run: hugo

      - name: Deploy to GitHub Pages
        uses: actions/deploy-github-pages@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # Replace with your desired branch
          directory: public
